- id: '1575527448382'
  alias: FristRun
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - alias: ''
    data:
      message: '1.本固件预集成了HACS，请到配置->集成->搜索并添加HACS。


        2.在MotionEye里添加好摄像头，即可显示在首页，或者配对苹果家庭，配对代码: 031-45-154 。


        3.集成ESPHome 方便用来增加ESPHome节点。


        4.Configuarator调用API，可从右侧菜单直接重启Home Assistant。


        5.Music可以播放本地MP3文件，资源管理器输入HA的ip地址，即可访问共享目录。


        更多教程：http://1t.click/avAU

        电报  群：http://1t.click/avAX

        电报频道：http://1t.click/avBs

        Twitter ：http://1t.click/avBg

        Facebook：http://1t.click/avBn

        '
      title: 使用提示
    service: persistent_notification.create
