- alias: Walking In Living Room Turns On Radiator
  description: 'Using Living Room Sensor'
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0003140ea8
    for: 
      seconds: '1'
    from: 'off'
    platform: state
    to: 'on'
  condition: 
  - entity_id: climate.living_room
    hvac_mode: off
  action:
    service: climate.set_hvac_mode
    data:
        entity_id: climate.living_room
        hvac_mode: auto

- alias: No One In Living Room For 30 Min Turns Off Radiator
  description: 'Using Living Room Sensor'
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0003140ea8
    for: 
      minutes: '30'
    platform: state
    to: 'off'
  condition: []
  action:
    service: climate.set_hvac_mode
    data:
        entity_id: climate.living_room
        hvac_mode: off

- alias: Walking In Ground Floor Turns On Kitchen Radiator
  description: 'Using Ground Floor Motion Sensor'
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d000171bd29
    for: 
      seconds: '1'
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.kitchen
        hvac_mode: auto
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.ground_floor_toilet
        hvac_mode: auto

- alias: No One In Ground Floor For 30 Min Turns Off Kitchen Radiator
  description: 'Using Living Room Sensor'
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0003140ea8
    for: 
      minutes: '30'
    platform: state
    to: 'off'
  condition: []
  action:
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.kitchen
        hvac_mode: 'off'
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.ground_floor_toilet
        hvac_mode: 'off'



