- id: '1603640029617'
  alias: Kitchen Lights On If Person Present and Dark In Daytime
  description: ''
  trigger:
  - entity_id: binary_sensor.kitchen_table_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  - entity_id: binary_sensor.kitchen_worktop_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.kitchen_table_motion_sensor_motion
        state: 'on'
      - below: '50'
        condition: numeric_state
        entity_id: sensor.kitchen_table_motion_sensor_light
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.kitchen_worktop_motion_sensor_motion
        state: 'on'
      - below: '50'
        condition: numeric_state
        entity_id: sensor.kitchen_worktop_motion_sensor_light
    - after: '6:00:00'
      before: '23:59:59'
      condition: time
  action:
  - data: {}
    service: script.kitchen_all_lights_turn_on
  mode: single
