# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


# TODO:
# 1. use single press instead of double press to turn off lights
# 2. [DONE] use homekit led for bed led to remove noise - however noise is still there
# 3. adapt the entrance light colour to yellow in the night
# 4. bedside lights colour control by button
# 5. bed lights colour control by day in the week/mode:sleep etc
# 6. Sleeping in the day time in the master room can stop heating and never turn back on
#    this is because turn on heating requires entering to the room. Change this using bed motion.
#    Also it is worth to solve sleeping in the day time for the other room - maybe uses a switch instead.
#    or using same method but having one more extra sensor per room for the door entrance logics.
# 7. Fixed the living room light switches.
#
#xiaomi_aqara:
#  discovery_retry: 5
#  gateways: # XiaoMi Gateway
#    - key: 153EEFE707B24CFB
#      mac: 34CE008D7558

#yeelight:
#  devices:
#    192.168.1.23:
#      name: Master Room Lamp Near Wall
#    192.168.1.26:
#      name: Master Room Lamp Near Door
#    192.168.1.22:
#      name: Living Room LED strip
#    192.168.1.25:
#      name: Master Room LED strip


# Added MagicHome LEDs
light:
  - platform: flux_led
    devices:
      192.168.1.29:
        name: spare_wifi_led
        mode: "rgb"

tado:
  username: !secret tado_user
  password: !secret tado_pass

hive:
  username: !secret hive_user
  password: !secret hive_pass
#  scan_interval: 2

# SwitchBot
switch:
  - platform: switchbot
    mac: 'CA:5F:F8:B5:68:EA'

sensor:
  # Time
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
  # XiaoMi BLE Temperature Sensor
  - platform: mitemp_bt
    period: 60
    encryptors:
               # En-suite Room Temperature Sensor
               'A4:C1:38:B0:EB:53': '71d88c34719d0708221d348fd14873dd'
               # En-suite Toilet Temperature Sensor
               'A4:C1:38:C2:C8:7A': '46244a59383e1183953324aed271cc32'
               # Guest Room Temperature Sensor
               'A4:C1:38:8C:F9:84': '996b9535497ced8bc997d5b6e209e74c'
               # Master Room Temperature Sensor
               #'A4:C1:38:CF:C7:01': ''
               # Kitchen Temperature Sensor
               #'A4:C1:38:0E:91:A7': 'f9696fa47ac23090eea383b520ff9a10'
               # Living Room Temperature Sensor
               'A4:C1:38:EC:DB:BA': '1b535cbb3e68651bd67157ee0775e5cb'
               # Kitchen Worktop Temperature Sensor
               #'58:2d:34:3b:6a:27'
  # Xiaomi BLE Round Fast Update Temperature Sensor
  - platform: mitemp_bt
    period: 5 # seconds for refresh interval
    sensor_names:
      '58:2d:34:3b:6a:27': 'Kitchen Hob Temperature Sensor'

# TVs
samsungtv:
  - host: 192.168.1.31
    name: Living Room TV

#media_player:
#  - platform: samsungtv_tizen
#    host: 192.168.1.30
#    port: 8002
#    mac: D0:03:DF:DB:89:AC
#    #name: Master Room TV

#device_tracker:
# - platform: tado
#   username: !secret tado_user
#   password: !secret tado_pass
#  - platform: xiaomi
#    host: 192.168.1.11
#    password: !secret xiaomi_admin_pass
#    interval_seconds: 10
#    consider_home: 180
#    new_device_defaults:
#      track_new_devices: false

# Apple HomeKit
#homekit:
#  auto_start: true

# Text to speech
#tts:
#  - platform: google_translate

# Database logging config
recorder:
  purge_keep_days: 10
  auto_purge: true
  commit_interval: 10 # updates log every 10s


group:          !include groups.yaml
automation:     !include_dir_merge_list automations/
automation gui: !include automations.yaml
script:         !include scripts.yaml


# Custom Variables
input_boolean:
  master_room_left_blind_moving_in_progress:
    name: 'Master Room Left Blind Moving In Progress'
    initial: 'off'

  master_room_left_blind_is_open:
    name: 'Master Room Left Blind Is Open'

  master_room_right_blind_moving_in_progress:
    name: 'Master Room Right Blind Moving In Progress'
    initial: 'off'

  master_room_right_blind_is_open:
    name: 'Master Room Right Blind Is Open'

  master_room_curtain_moving_in_progress:
    name: 'Master Room Curtain Moving In Progress'
    initial: 'off'

  master_room_curtain_is_open:
    name: 'Master Room Curtain Is Open'

  en_suite_room_guests_use_this_room:
    name: 'En-suite Room Guests Use This Room'

  guest_room_guests_use_this_room:
    name: 'Guest Room Guests Use This Room'

# Port some thrid party products to Homekit for easy UI control
homekit:
- filter:
    include_entities:
    # Misc
    # Master Room
      - binary_sensor.master_room_tv_motion_sensor_motion
      - binary_sensor.master_room_stair_motion_sensor_motion
      - binary_sensor.master_room_dressing_table_motion_sensor_motion
      - binary_sensor.master_room_drawer_motion_sensor_motion
      - binary_sensor.master_room_bed_motion_sensor_motion
      - binary_sensor.master_toilet_basin_motion_sensor_motion
      - binary_sensor.master_toilet_shower_motion_sensor_motion
      - binary_sensor.master_toilet_dressing_motion_sensor_motion
      - sensor.master_room_light_meter
      - climate.master_room
      - climate.master_toilet
      - cover.master_room_curtain
      - cover.master_room_blind_left
      - cover.master_room_blind_right
      - light.master_room_lamp_near_door
      - light.master_room_lamp_near_wall
      - light.master_room_bed_led
      - light.master_room_entrance_led_light
      - switch.master_room_dressing_table_light
      - switch.master_room_bed_ceiling_light
      - switch.master_room_landing_ceiling_light
      - switch.master_room_balcony_decro_light
      - switch.master_toilet_dressing_light
      - switch.master_toilet_light
      - switch.master_toilet_floor_led
    # Living Room
      - media_player.living_room # Sonos
      - climate.living_room
      - light.living_room_ble_light_near_door
      - light.living_room_ble_light_near_wall
      - switch.living_room_ceiling_light
      - switch.living_room_tree_light
      - switch.garden_light
      - switch.garden_extension_lead_switch_1      
      - switch.garden_extension_lead_switch_2
      - switch.garden_extension_lead_switch_3      
    # Kitchen
      - binary_sensor.kitchen_table_motion_sensor_motion
      - binary_sensor.kitchen_worktop_motion_sensor_motion
      - media_player.kitchen # Sonos
      - climate.kitchen
      - sensor.mi_temperature_kitchen_hob_temperature_sensor
      - switch.kitchen_drinking_hot_water
      - switch.kitchen_led_left_13815882
      - switch.kitchen_led_right_97186274
      - switch.kitchen_ceiling_light
      - switch.kitchen_dining_light
      - switch.kitchen_floor_led
      - switch.kitchen_extractor
      - switch.kitchen_decro_light
    # Guest Room
      - input_boolean.guest_room_guests_use_this_room
      - climate.guest_room
      - climate.guest_toilet
      - switch.guest_room_ceiling_light
      - switch.guest_room_screen_led
      - switch.guest_toilet_ceiling_light
      - switch.guest_toilet_floor_led
    # En-suite Room
      - input_boolean.en_suite_room_guests_use_this_room
      - climate.en_suite_room
      - climate.en_suite_toilet
      - sensor.temp_of_en_suite_room
      - switch.en_suite_room_ceiling_light
      - switch.en_suite_toilet_light
      - switch.en_suite_room_bedside_lamp
    # Ground Toilet
      - climate.ground_toilet
      - switch.ground_toilet_light
    # Corridor
      - binary_sensor.first_corridor_motion_sensor_motion
      - binary_sensor.ground_corridor_motion_sensor_motion    
      - media_player.first_corridor # Sonos
      - climate.ground_floor_corridor
      - light.first_corridor_ble_light
      - light.ground_corridor_ble_light
      # Always ON Switch
      - switch.front_door_light_switch
      - switch.ground_corridor_light_switch
      - switch.first_corridor_light_switch
      - switch.master_room_entrance_light_switch
      # Zone Heating
      - switch.downstairs_heating
      - switch.upstairs_heating
      - switch.water_heater
      # Water Heater Scheudle
      - automation.water_heater_on_schedule
    # Study
      - climate.study
      - switch.study_light
