# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

discovery:
  ignore:
    - yeelight
yeelight:
  devices:
    192.168.1.23:
      name: Master Room Lamp 1
    192.168.1.26:
      name: Master Room Lamp 2
    192.168.1.22:
      name: Living Room LED strip
    192.168.1.25:
      name: Master Room LED strip
      
tado:
  username: !secret tado_user
  password: !secret tado_pass

hive:
  username: !secret hive_user
  password: !secret hive_pass
  scan_interval: 2 
  
sensor:
  # Time
  - platform: time_date
    display_options:
      - 'time'
      - 'date'


#device_tracker:
# - platform: tado
#   username: !secret tado_user
#   password: !secret tado_pass
#  - platform: xiaomi
#    host: 192.168.1.11
#    password: !secret xiaomi_admin_pass
#    interval_seconds: 10
#    consider_home: 180    
#    new_device_defaults:
#      track_new_devices: false

# Apple HomeKit
#homekit:
#  auto_start: true

# Text to speech
#tts:
#  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

