# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

#introduction:
xiaomi_aqara:
  discovery_retry: 5
  gateways: # XiaoMi Gateway
    - key: 153EEFE707B24CFB
      mac: 34CE008D7558

discovery:

tado:
  username: !secret tado_user
  password: !secret tado_pass

hive:
  username: !secret hive_user
  password: !secret hive_pass

device_tracker:
# - platform: tado
#   username: !secret tado_user
#   password: !secret tado_pass
  - platform: xiaomi
    host: 192.168.1.11
    password: !secret xiaomi_admin_pass
    interval_seconds: 10
    consider_home: 180    
    new_device_defaults:
      track_new_devices: false

# Apple HomeKit
homekit:
  auto_start: true

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
#automation: !include automations.yaml
script: !include scripts.yaml



