# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


# TODO:
# * adapt the entrance light colour to yellow in the night
# * bedside lights colour control by button/homekit
# * bed lights colour control by day in the week/mode/sleep etc
# * Fixed the living room light switches.
# * move automation to be package based - check if we can use a shared package for shared code
# * delay heating on en-suite room and moved that to thermostat based control like master room
# * master toilet light 
#.  - dim version in the night
#.  - color change depends on mirror on/off 
#.  - if color is white, turn off floor warm led
# * use motion sensor light to tell if people is up but still stay at the room to adjust temp in the morning
#
#xiaomi_aqara:
#  discovery_retry: 5
#  gateways: # XiaoMi Gateway
#    - key: 153EEFE707B24CFB
#      mac: 34CE008D7558
#
#
#yeelight:
#  devices:
#    192.168.1.23:
#      name: Master Room Lamp Near Wall
#    192.168.1.26:
#      name: Master Room Lamp Near Door
#    192.168.1.22:
#      name: Living Room LED strip
#    192.168.1.25:
#      name: Master Room LED strip

# Customize binary sensor
binary_sensor:
  - platform: template
    sensors:
      master_toilet_mirror_light:
        friendly_name: "Master Toilet Mirror Light"
        value_template: >-
          {{ states('sensor.master_toilet_mirror_light_meter')|int > 1000 }}

# Added MagicHome LEDs
# This is a third-party custom component on flux_led 
# instead of the official one from HA
light:
  - platform: flux_led
    devices:
      192.168.1.29:
        name: spare_wifi_led
        mode: "rgb"



###########################################
# Light Groups
###########################################
light mt_group:
  - platform: group
    name: Master Toilet Ceiling Light
    entities:
      - light.master_toilet_spotlight_bulb_1
      - light.master_toilet_spotlight_bulb_2
      - light.master_toilet_spotlight_bulb_3
      - light.master_toilet_spotlight_bulb_4


tado:
  username: !secret tado_user
  password: !secret tado_pass


sensor:
  # Time
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
#  # XiaoMi BLE Temperature Sensor
#  - platform: mitemp_bt
#    period: 60
#    encryptors:
#               # En-suite Room Temperature Sensor
#               'A4:C1:38:B0:EB:53': '71d88c34719d0708221d348fd14873dd'
#               # En-suite Toilet Temperature Sensor
#               'A4:C1:38:C2:C8:7A': '46244a59383e1183953324aed271cc32'
#               # Guest Room Temperature Sensor
#               'A4:C1:38:8C:F9:84': '996b9535497ced8bc997d5b6e209e74c'
#               # Master Room Temperature Sensor
#               #'A4:C1:38:CF:C7:01': ''
#               # Kitchen Temperature Sensor
#               #'A4:C1:38:0E:91:A7': 'f9696fa47ac23090eea383b520ff9a10'
#               # Living Room Temperature Sensor
#               'A4:C1:38:EC:DB:BA': '1b535cbb3e68651bd67157ee0775e5cb'
#               # Kitchen Worktop Temperature Sensor
#               #'58:2d:34:3b:6a:27'
  # Xiaomi BLE Round Fast Update Temperature Sensor
  - platform: mitemp_bt
    period: 5 # seconds for refresh interval
    sensor_names:
      '58:2d:34:3b:6a:27': 'Kitchen Hob Temperature Sensor'

# TVs
#samsungtv:
#  - host: 192.168.1.31
#    name: Living Room TV

#media_player:
#  - platform: samsungtv_tizen
#    host: 192.168.1.30
#    port: 8002
#    mac: D0:03:DF:DB:89:AC
#    #name: Master Room TV

#device_tracker:
# - platform: tado
#   username: !secret tado_user
#   password: !secret tado_pass
#  - platform: xiaomi
#    host: 192.168.1.11
#    password: !secret xiaomi_admin_pass
#    interval_seconds: 10
#    consider_home: 180
#    new_device_defaults:
#      track_new_devices: false


# Database logging config
recorder:
  purge_keep_days: 1
  auto_purge: true
  commit_interval: 10 # updates log every 10s

# Install Mini Media Player
#resources:
#  - url: /local/mini-media-player-bundle.js?v=1.11.0
#    type: module

group:          !include groups.yaml
automation:     !include_dir_merge_list automations/
automation gui: !include automations.yaml
script:         !include scripts/tais_scripts.yaml
#script gui:     !include scripts.yaml


# Custom Thermostat 
climate:
  - platform: generic_thermostat
    name: En-suite Room Thermostat
    heater: input_boolean.en_suite_room_valve_switch
    target_sensor: sensor.en_suite_room_temperature_sensor
    precision: 0.1
    min_temp: 10
    max_temp: 25
    cold_tolerance: 0.1
    hot_tolerance:  0.1
    initial_hvac_mode: 'heat'
    
  - platform: generic_thermostat
    name: Master Room Thermostat
    heater: input_boolean.master_room_valve_switch
    target_sensor: sensor.master_room_temperature_sensor
    precision: 0.1
    min_temp: 10
    max_temp: 25
    cold_tolerance: 0.1
    hot_tolerance:  0.1
    initial_hvac_mode: 'heat'

  - platform: generic_thermostat
    name: Guest Room Thermostat
    heater: input_boolean.guest_room_valve_switch
    target_sensor: sensor.guest_room_temperature_sensor
    precision: 0.1
    min_temp: 10
    max_temp: 25
    cold_tolerance: 0.1
    hot_tolerance:  0.1
    initial_hvac_mode: 'heat'


###########################################
# Custom Variables
###########################################
input_boolean:
  ####################################
  # Tuya Curtains Variables 
  ####################################
  master_room_left_blind_moving_in_progress:
    name: 'Master Room Left Blind Moving In Progress'
    initial: 'off'

  master_room_left_blind_is_open:
    name: 'Master Room Left Blind Is Open'

  master_room_right_blind_moving_in_progress:
    name: 'Master Room Right Blind Moving In Progress'
    initial: 'off'

  master_room_right_blind_is_open:
    name: 'Master Room Right Blind Is Open'

  master_room_curtain_moving_in_progress:
    name: 'Master Room Curtain Moving In Progress'
    initial: 'off'

  master_room_curtain_is_open:
    name: 'Master Room Curtain Is Open'

  ####################################
  # Spare Room Usage
  ####################################
  en_suite_room_guests_use_this_room:
    name: 'En-suite Room Guests Use This Room'

  guest_room_guests_use_this_room:
    name: 'Guest Room Guests Use This Room'

  ####################################
  # Music Followers
  ####################################
  follow_music:
    name: 'Follow Music'

  ####################################
  # Custom Thermostat Switch
  ####################################
  en_suite_room_valve_switch:
    name: 'En-suite Room Valve Switch'

  master_room_valve_switch:
    name: 'Master Room Valve Switch'

  guest_room_valve_switch:
    name: 'Guest Room Valve Switch'

  ####################################
  # First Time Presence in a Room
  ####################################
  master_room_short_presence: # done
    name: 'Master Room Short Presence'

  master_toilet_short_presence: # done
    name: 'Master Toilet Short Presence'

  kitchen_short_presence: # done
    name: 'Kitchen Short Presence'

  living_room_short_presence: # done
    name: 'Living Room Short Presence'

  ground_toilet_short_presence: # done
    name: 'Ground Toilet Short Presence'

  guest_room_short_presence: # done
    name: 'Guest Room Short Presence'
    
  guest_toilet_short_presence: # done
    name: 'Ground Toilet Short Presence'
    
  en_suite_room_short_presence: 
    name: 'En-suite Room Short Presence'
    
  en_suite_toilet_short_presence: 
    name: 'En-suite Toilet Short Presence'
        
        
input_select:
  music_controller:
    name: Sonos Music Master Speaker
    options:
      - master_room_sonos
      - kitchen_sonos
      - living_room_sonos
      - first_corridor_sonos
      
# Port some thrid party products to Homekit for easy UI control
homekit:
- filter:
    include_entities:
    # Misc
    # Master Room
      - binary_sensor.master_room_tv_motion_sensor_motion
      - binary_sensor.master_room_stair_motion_sensor_motion
      - binary_sensor.master_room_dressing_table_motion_sensor_motion
      - binary_sensor.master_room_drawer_motion_sensor_motion
      - binary_sensor.master_room_bed_motion_sensor_motion
      - binary_sensor.master_toilet_basin_motion_sensor_motion
      - binary_sensor.master_toilet_shower_motion_sensor_motion
      - binary_sensor.master_toilet_dressing_motion_sensor_motion
      - binary_sensor.master_toilet_door
      - sensor.master_room_light_meter
      #- sensor.master_room_bedside_button
      #- sensor.master_room_six_key_button
      #- sensor.master_room_spare_button
      #- climate.master_room  # tado
      - climate.master_room_thermostat
      - climate.master_toilet
      - switch.master_room_tv
      - cover.master_room_curtain
      - cover.master_room_blind_left
      - cover.master_room_blind_right
      - light.master_room_lamp_near_door
      - light.master_room_lamp_near_wall
      - light.master_room_bed_led
      - light.master_room_entrance_led_light
      - light.master_toilet_ceiling_light      
      - switch.master_room_dressing_table_light
      - switch.master_room_bed_ceiling_light
      - switch.master_room_landing_ceiling_light
      - switch.master_room_balcony_decro_light
      - switch.master_toilet_dressing_light
      - switch.master_toilet_floor_led
      - switch.master_toilet_light
    # Living Room
      - binary_sensor.living_room_tv_motion_sensor_motion
      - binary_sensor.living_room_sofa_motion_sensor_motion
      - binary_sensor.garden_sliding_door_motion_sensor_motion
      - binary_sensor.garden_bike_shed_motion_sensor_motion
      - binary_sensor.garden_door
      - media_player.living_room_sonos 
      #- sensor.living_room_sofa_button
      - climate.living_room
      - switch.living_room_tv
      - light.living_room_ble_light_near_door
      - light.living_room_ble_light_near_wall
      - switch.living_room_ceiling_light
      - switch.living_room_tree_light
      - switch.garden_light
      - switch.garden_extension_lead_switch_1      
      - switch.garden_extension_lead_switch_2
      - switch.garden_extension_lead_switch_3      
    # Kitchen
      - binary_sensor.kitchen_table_motion_sensor_motion
      - binary_sensor.kitchen_worktop_motion_sensor_motion
      #- sensor.kitchen_worktop_button
      - media_player.kitchen_sonos
      - climate.kitchen
      - sensor.mi_temperature_kitchen_hob_temperature_sensor
      - switch.kitchen_tv
      - switch.kitchen_drinking_hot_water
      - switch.kitchen_led_left_13815882
      - switch.kitchen_led_right_97186274
      - switch.kitchen_ceiling_light
      - switch.kitchen_dining_light
      - switch.kitchen_floor_led
      - switch.kitchen_extractor
      - switch.kitchen_decro_light
    # Guest Room
      - binary_sensor.guest_room_radiator_motion_sensor_motion
      - binary_sensor.guest_room_bed_motion_sensor_motion
      - binary_sensor.guest_toilet_motion_sensor_motion
      - binary_sensor.guest_toilet_door
      - input_boolean.guest_room_guests_use_this_room
      #- sensor.guest_room_button
      #- climate.guest_room  # tado
      - climate.guest_room_thermostat
      - climate.guest_toilet
      - switch.guest_room_ceiling_light
      - switch.guest_room_screen_led
      - switch.guest_toilet_ceiling_light
      - switch.guest_toilet_floor_led
    # En-suite Room
      - binary_sensor.en_suite_room_motion_sensor_motion
      - binary_sensor.en_suite_toilet_motion_sensor_motion
      - binary_sensor.en_suite_toilet_door
      - input_boolean.en_suite_room_guests_use_this_room
      #- sensor.en_suite_room_bedside_button
      #- climate.en_suite_room # tado
      - climate.en_suite_room_thermostat
      - climate.en_suite_toilet
      - sensor.temp_of_en_suite_room
      - switch.en_suite_room_ceiling_light
      - switch.en_suite_toilet_light
      - switch.en_suite_room_bedside_lamp
    # Ground Toilet
      - binary_sensor.ground_toilet_motion_sensor_motion
      - binary_sensor.ground_toilet_door
      - climate.ground_toilet
      - switch.ground_toilet_light
    # Corridor
      - binary_sensor.front_door_motion_sensor_motion
      - binary_sensor.first_corridor_motion_sensor_motion
      - binary_sensor.ground_corridor_motion_sensor_motion    
      - media_player.first_corridor_sonos
      - climate.ground_floor_corridor
      - light.first_corridor_ble_light
      - light.ground_corridor_ble_light
      - switch.corridor_decro_light
      # Always ON Switch
      - switch.front_door_light_switch
      - switch.ground_corridor_light_switch
      - switch.first_corridor_light_switch
      - switch.master_room_entrance_light_switch
      # Zone Heating
      - switch.downstairs_heating
      - switch.upstairs_heating
      - switch.water_heater
      # Water Heater Scheudle
      - automation.water_heater_on_schedule
      # Sonos Music Follower
      - input_boolean.follow_music
    # Study
      - binary_sensor.study_motion_sensor_motion
      #- sensor.study_button
      - climate.study
      - switch.study_light
