# Christams Decro Lights Automation
# In Kitchen/Master Room/Garden
#
###############################################
#
# Light Automation based on motion sensors
#
###############################################

# Master Room Balcony
- alias: L-MR Master Room Balcony And Indoor Light On If Curtain Open
  description: ''
  trigger:
  - platform: state
    entity_id: 
      - cover.master_room_blind_left
      - cover.master_room_blind_right
      - cover.master_room_curtain
    from: 'closed'
    to: 'open'
  - platform: state
    from: 'off'
    to: 'on'
    entity_id:
      - binary_sensor.ground_corridor_motion_sensor_motion
      - binary_sensor.first_corridor_motion_sensor_motion
      - binary_sensor.master_room_entrance_motion_sensor
      - binary_sensor.master_room_stair_motion_sensor_motion
  condition: []
  action:
  - service: switch.turn_on
    entity_id: switch.master_room_balcony_decro_light



- alias: L-MR Master Room Balcony Light Off If Curtain Closed
  description: ''
  trigger:
  - minutes: /3
    platform: time_pattern
  condition: 
  - condition: and
    conditions:
    - condition: state
      state: 'closed'
      entity_id:
        - cover.master_room_blind_left
        - cover.master_room_blind_right
        - cover.master_room_curtain  
    - condition: state
      state: 'off'
      for: 00:03:00
      entity_id:
        - binary_sensor.ground_corridor_motion_sensor_motion
        - binary_sensor.first_corridor_motion_sensor_motion
        - binary_sensor.master_room_entrance_motion_sensor
        - binary_sensor.master_room_stair_motion_sensor_motion
  action:
  - service: switch.turn_off
    entity_id: switch.master_room_balcony_decro_light



# Kitchen Decro Lights
- alias: L-LR Kitchen Decro Lights On If People Are Around
  description: ''
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    entity_id:
      - binary_sensor.ground_corridor_motion_sensor_motion
      - binary_sensor.first_corridor_motion_sensor_motion
      - binary_sensor.kitchen_table_motion_sensor_motion
      - binary_sensor.kitchen_worktop_motion_sensor_motion
  condition: []
  action:
  - service: switch.turn_on
    entity_id: switch.kitchen_decro_light


- alias: L-KC Kitchen Decro Lights Off If People Are Not Around
  description: ''
  trigger:
  - minutes: /3
    platform: time_pattern
  condition:
  - condition: state
    state: 'off'
    for: 00:05:00
    entity_id:
      - binary_sensor.ground_corridor_motion_sensor_motion
      - binary_sensor.kitchen_table_motion_sensor_motion
      - binary_sensor.kitchen_worktop_motion_sensor_motion
  action:
  - service: switch.turn_off
    entity_id: switch.kitchen_decro_light



# Living Room Christmas Tree Light
- alias: L-LR Living Room Christmas Tree Lights On If People Are Around
  description: ''
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    entity_id:
      - binary_sensor.living_room_sofa_motion_sensor_motion
      - binary_sensor.living_room_tv_motion_sensor_motion
      - binary_sensor.garden_sliding_door_motion_sensor_motion
      - binary_sensor.garden_bike_shed_motion_sensor_motion
      - binary_sensor.ground_corridor_motion_sensor_motion
      - binary_sensor.first_corridor_motion_sensor_motion
  condition: []
  action:
  - service: switch.turn_on
    entity_id:
      - switch.living_room_tree_light


- alias: L-LR Living Room Christmas Tree Lights Off If People Are Not Around
  description: ''
  trigger:
  - minutes: /3
    platform: time_pattern
  condition:
  - condition: state
    entity_id:
      - binary_sensor.living_room_sofa_motion_sensor_motion
      - binary_sensor.living_room_tv_motion_sensor_motion
      - binary_sensor.garden_sliding_door_motion_sensor_motion
      - binary_sensor.garden_bike_shed_motion_sensor_motion
      - binary_sensor.ground_corridor_motion_sensor_motion
      - binary_sensor.first_corridor_motion_sensor_motion
    state: 'off'
    for: 00:05:00
  action:
  - service: switch.turn_off
    entity_id:
      - switch.living_room_tree_light




# Garden Decro Lights
- alias: L-LR Garden Decro Lights On If People Are Around
  description: ''
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    entity_id:
      - binary_sensor.living_room_sofa_motion_sensor_motion
      - binary_sensor.living_room_tv_motion_sensor_motion
      - binary_sensor.garden_sliding_door_motion_sensor_motion
      - binary_sensor.garden_bike_shed_motion_sensor_motion
      - binary_sensor.ground_corridor_motion_sensor_motion
      - binary_sensor.first_corridor_motion_sensor_motion
      - binary_sensor.master_toilet_dressing_motion_sensor_motion
      - binary_sensor.master_toilet_basin_motion_sensor_motion
      - binary_sensor.master_toilet_shower_motion_sensor_motion
  condition:
  - condition: numeric_state
    entity_id: sensor.master_room_light_meter
    below: '30'
  action:
  - service: switch.turn_on
    entity_id:
      - switch.garden_extension_lead_switch_2
      - switch.garden_extension_lead_switch_3


- alias: L-LR Garden Decro Lights Off If People Are Not Around
  description: ''
  trigger:
  - minutes: /3
    platform: time_pattern
  condition:
  - condition: state
    state: 'off'
    for: 00:05:00
    entity_id:
      - binary_sensor.living_room_sofa_motion_sensor_motion
      - binary_sensor.living_room_tv_motion_sensor_motion
      - binary_sensor.garden_sliding_door_motion_sensor_motion
      - binary_sensor.garden_bike_shed_motion_sensor_motion
      - binary_sensor.ground_corridor_motion_sensor_motion
      - binary_sensor.first_corridor_motion_sensor_motion
      - binary_sensor.master_toilet_dressing_motion_sensor_motion
      - binary_sensor.master_toilet_basin_motion_sensor_motion
      - binary_sensor.master_toilet_shower_motion_sensor_motion
  action:
  - service: switch.turn_off
    entity_id:
      - switch.garden_extension_lead_switch_2
      - switch.garden_extension_lead_switch_3
