# Ground Toielt
# Ground Corrdior
# Downstairs Zone
# Upstairs Zone
# - Heating automation
# - Lighting automation based on motion sensors
# - Lighting automation based on buttons


###############################################
#
# Heating Automation based on motion sensors
#
###############################################

- alias: H-0T Ground Toilet Heating Set to 20 If Person Present
  id: '11122334455000'
  description: 'automation.ground_toilet_heating_on_if_people_present'
  trigger:
  - entity_id: binary_sensor.ground_toilet_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition: []
  action:
  - entity_id: climate.ground_toilet
    service: climate.set_hvac_mode
    data:
      hvac_mode: heat
  - service: climate.set_temperature
    entity_id: climate.ground_toilet
    data:
      temperature: 20




- alias: H-0T Ground Toilet Heating Off If No Person for 10 Min
  id: '1599605792677'
  description: 'automation.ground_toilet_heating_off_if_no_person'
  trigger:
  - entity_id: binary_sensor.ground_toilet_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:10:00
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: state
    entity_id: binary_sensor.ground_toilet_motion_sensor_motion
    for: 00:10:00
    state: 'off'
  action:
  - service: climate.set_hvac_mode
    entity_id: climate.ground_toilet
    data:
      hvac_mode: auto
  - data: {}
    entity_id: automation.ground_toilet_heating_on_if_people_present
    service: automation.turn_on





- alias: H-GC Ground Corrdior Heating Set to 20 If Person Present
  id: '1599611792932'
  description: 'automation.ground_corrdior_heating_on_if_person_present'
  trigger:
  - entity_id: binary_sensor.ground_corridor_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition: []
  action:
  - data:
      hvac_mode: heat
    entity_id: climate.ground_floor_corridor
    service: climate.set_hvac_mode
  - data:
      temperature: 20
    entity_id: climate.ground_floor_corridor
    service: climate.set_temperature





- alias: H-GC Ground Corridor Heating Off If No Person For 20 Min
  id: '1599611696918'
  description: 'automation.ground_corridor_heating_off_if_no_person'
  trigger:
  - entity_id: binary_sensor.ground_corridor_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:20:00
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.ground_corridor_motion_sensor_motion
      for: 00:20:00
      state: 'off'
    - condition: state
      entity_id: binary_sensor.first_corridor_motion_sensor_motion
      for: 00:20:00
      state: 'off'
  action:
  - service: climate.set_hvac_mode
    entity_id: climate.ground_floor_corridor
    data:
      hvac_mode: auto





- alias: H-DS Downstairs Zone Heating On If Person Present
  id: '1599612133872'
  description: 'automation.downstairs_zone_heating_on_if_person_present'
  trigger:
  - entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  - entity_id: binary_sensor.kitchen_table_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  - entity_id: binary_sensor.ground_corridor_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  - entity_id: binary_sensor.ground_toilet_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    entity_id: switch.downstairs_heating




- alias: H-DS Downstairs Zone Heating Off If No Person For 10 Min
  id: '1599653387645'
  description: 'automation.downstairs_zone_heating_off_if_no_person'
  trigger:
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.ground_corridor_motion_sensor_motion
      state: 'off'
      for: 00:10:00
    - condition: state
      entity_id: binary_sensor.ground_toilet_motion_sensor_motion
      state: 'off'
      for: 00:10:00
    - condition: state
      entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
      state: 'off'
      for: 00:10:00
    - condition: state
      entity_id: binary_sensor.living_room_tv_motion_sensor_motion
      state: 'off'
      for: 00:10:00
    - condition: state
      entity_id: binary_sensor.kitchen_table_motion_sensor_motion
      state: 'off'
      for: 00:10:00
    - condition: state
      entity_id: binary_sensor.kitchen_worktop_motion_sensor_motion
      state: 'off'
      for: 00:10:00
  action:
  - service: switch.turn_off
    entity_id: switch.downstairs_heating




- alias: H-US Upstairs Zone Heating On If Person Present
  id: '1600016150575'
  description: 'automation.upstairs_zone_heating_on_if_person_present'
  trigger:
  - entity_id: binary_sensor.master_toilet_basin_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  - entity_id: binary_sensor.master_toilet_shower_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  - entity_id: binary_sensor.master_room_bed_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  - entity_id: binary_sensor.study_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  - entity_id: binary_sensor.guest_toilet_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  - entity_id: binary_sensor.guest_room_radiator_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  - entity_id: binary_sensor.guest_room_bed_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  - entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  - entity_id: binary_sensor.en_suite_room_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    entity_id: switch.upstairs_heating



- alias: H-US Upstairs Zone Heating Off If No Person For 20 Min In Daytime
  id: '1600017150562'
  description: 'automation.upstairs_zone_heating_off_if_no_person_in_daytime'
  trigger:
  - minutes: /5
    platform: time_pattern
  condition: []
  action:
  - choose:
    # IF - in daytime, turn off in 20 min
    - conditions:
      - after: '9:00:00'
        before: '21:00:00'
        condition: time
      - condition: state
        entity_id: binary_sensor.master_toilet_basin_motion_sensor_motion
        state: 'off'
        for: 00:20:00
      - condition: state
        entity_id: binary_sensor.master_toilet_shower_motion_sensor_motion
        state: 'off'
        for: 00:20:00
      - condition: state
        entity_id: binary_sensor.master_room_bed_motion_sensor_motion
        state: 'off'
        for: 00:20:00
      - condition: state
        entity_id: binary_sensor.study_motion_sensor_motion
        state: 'off'
        for: 00:20:00
      - condition: state
        entity_id: binary_sensor.guest_room_radiator_motion_sensor_motion
        state: 'off'
        for: 00:20:00
      - condition: state
        entity_id: binary_sensor.guest_room_bed_motion_sensor_motion
        state: 'off'
        for: 00:20:00
      - condition: state
        entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
        state: 'off'
        for: 00:20:00
      - condition: state
        entity_id: binary_sensor.en_suite_room_motion_sensor_motion
        state: 'off'
        for: 00:20:00
      sequence:
      - service: switch.turn_off
        entity_id: switch.upstairs_heating
    # ELSE IF - in nighttime, turn off in 2 hours
    - conditions:
      - after: '21:00:00'
        before: '9:00:00'
        condition: time
      - condition: state
        entity_id: binary_sensor.master_toilet_basin_motion_sensor_motion
        state: 'off'
        for: 02:00:00
      - condition: state
        entity_id: binary_sensor.master_toilet_shower_motion_sensor_motion
        state: 'off'
        for: 02:00:00
      - condition: state
        entity_id: binary_sensor.master_room_bed_motion_sensor_motion
        state: 'off'
        for: 02:00:00
      - condition: state
        entity_id: binary_sensor.study_motion_sensor_motion
        state: 'off'
        for: 02:00:00
      - condition: state
        entity_id: binary_sensor.guest_room_radiator_motion_sensor_motion
        state: 'off'
        for: 02:00:00
      - condition: state
        entity_id: binary_sensor.guest_room_bed_motion_sensor_motion
        state: 'off'
        for: 02:00:00
      - condition: state
        entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
        state: 'off'
        for: 02:00:00
      - condition: state
        entity_id: binary_sensor.en_suite_room_motion_sensor_motion
        state: 'off'
        for: 02:00:00
      sequence:
      - service: switch.turn_off
        entity_id: switch.upstairs_heating


###############################################
#
# Lighting Automation based on motion sensors
#
###############################################

# Ground Toilet Lights
- alias: L-0T Ground Toilet Lights On If Person Present and Dark
  id: '1603640020013'
  description: ''
  trigger:
  - entity_id: binary_sensor.ground_toilet_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
  - condition: and
    conditions:
    - entity_id: binary_sensor.ground_toilet_motion_sensor_motion
      condition: state
      state: 'on'
    - entity_id: sensor.ground_toilet_motion_sensor_light
      condition: numeric_state
      below: '30'
  action:
  - data: {}
    entity_id: switch.ground_toilet_light
    service: switch.turn_on



- alias: L-0T Ground Toilet Lights Off If No Person For 10 Min
  id: '1603640020014'
  description: ''
  trigger:
  - entity_id: binary_sensor.ground_toilet_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:10:00
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: and
    conditions:
    - after: '00:00:01'
      before: '00:00:00'
      condition: time
    - entity_id: binary_sensor.ground_toilet_motion_sensor_motion
      condition: state
      state: 'off'
      for: 00:10:00
  action:
  - data: {}
    entity_id: switch.ground_toilet_light
    service: switch.turn_off



- alias: L-0T Ground Toilet Lights Off If No Person For 2 Min And Door Open
  id: '1603640020015'
  description: ''
  trigger:
  - entity_id: binary_sensor.ground_toilet_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:02:00
  condition:
  - condition: and
    conditions:
    - after: '00:00:01'
      before: '00:00:00'
      condition: time
    - entity_id: binary_sensor.ground_toilet_door
      condition: state
      state: 'on'
    - entity_id: binary_sensor.ground_toilet_motion_sensor_motion
      condition: state
      state: 'off'
      for: 00:02:00
  action:
  - data: {}
    entity_id: switch.ground_toilet_light
    service: switch.turn_off


# Corridors
- alias: L-GC Ground Corridor Lights On From Ground Floor If Person Present
  description: ''
  trigger:
  - entity_id: binary_sensor.ground_corridor_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
  - entity_id: binary_sensor.ground_corridor_motion_sensor_motion
    condition: state
    state: 'on'
  - entity_id: sensor.ground_corridor_motion_sensor_light
    condition: numeric_state
    below: '30'
  action:
  - service: script.corridor_lights_turn_on_from_ground_floor



- alias: L-GC Ground Corridor Lights On From First Floor If Person Present
  description: ''
  trigger:
  - entity_id: binary_sensor.first_corridor_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
  - entity_id: binary_sensor.first_corridor_motion_sensor_motion
    condition: state
    state: 'on'
  - entity_id: sensor.first_corridor_motion_sensor_light
    condition: numeric_state
    below: '30'
  action:
  - service: script.corridor_lights_turn_on_from_first_floor



- alias: L-GC Ground Corridor Lights Off If No Person For 2 Min
  description: ''
  trigger:
  - entity_id: binary_sensor.ground_corridor_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:02:00
  - entity_id: binary_sensor.first_corridor_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:02:00
  condition:
  - condition: state
    entity_id: binary_sensor.ground_corridor_motion_sensor_motion
    for: 00:02:00
    state: 'off'
  - condition: state
    entity_id: binary_sensor.first_corridor_motion_sensor_motion
    for: 00:02:00
    state: 'off'
  action:
  - data: {}
    service: script.corridor_lights_turn_off

################################################
#
# Lighting automation based on buttons
#
################################################

# Ground Toilet Lights
- alias: B-0T Ground Toilet Wall Switch - Single Press - Toggle Lights
  trigger:
  - entity_id: sensor.ground_toilet_light_wall_button
    platform: state
    to: button_2_single
  condition: []
  action:
  - service: switch.toggle
    entity_id: switch.ground_toilet_light


- alias: B-0T Ground Toilet Wall Switch - Single Press - Toggle Lights
  trigger:
  - entity_id: sensor.ground_toilet_light_wall_button
    platform: state
    to:
    - button_1_double
    - button_2_double
  condition: []
  action:
  - service: switch.turn_off
    entity_id: switch.ground_toilet_light

- alias: B-GC Ground Corridor Wall Switch - Doulbe Press - Turn Off Ground Floor Lights
  trigger:
  - entity_id: sensor.ground_corrdior_switch_wall_button
    platform: state
    to:
    - button_1_double
    - button_2_double
  condition: []
  action:
  - service: script.living_room_all_lights_turn_off
  - service: script.kitchen_all_lights_and_appliances_turn_off
  - service: switch.turn_off
    entity_id: switch.ground_toilet_light




