# En-suite Room
# En-suite Toilet
# - Heating automation
# - Lighting automation based on motion sensors
# - Lighting automation based on buttons
#


- alias: H-ER En-suite Room Heating Automation On If Person Present
  id: '1599909943111'
  description: 'automation.en_suite_room_heating_on_if_person_present'
  trigger:
  - entity_id: binary_sensor.en_suite_room_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition: []
  action:
  - entity_id: climate.en_suite_room
    service: climate.set_hvac_mode
    data:
      hvac_mode: heat
  - service: climate.en_suite_room
    entity_id: climate.ground_toilet
    data:
      temperature: 20
  - data: {}
    entity_id: automation.en_suite_room_heating_based_on_temerature_sensor
    service: automation.turn_on
  - data: {}
    entity_id: automation.en_suite_room_heating_on_if_person_present
    service: automation.turn_off
  mode: single





- alias: H-ER En-suite Room Heating Set to 22.5 Based on Temerature Sensor
  id: '1602027730610'
  description: 'automation.en_suite_room_heating_based_on_temerature_sensor'
  trigger:
  - minutes: /3
    platform: time_pattern
  condition: []
  action:
  - data:
      hvac_mode: heat
    entity_id: climate.en_suite_room
    service: climate.set_hvac_mode
  - data_template:
      temperature: '{% set temp = states(''sensor.temp_of_en_suite_room'')|float %}  {%
        if temp < 22.5 %} 25 {% else %} 5 {% endif %}

        '
    entity_id: climate.en_suite_room
    service: climate.set_temperature
  mode: single





- alias: H-ER En-suite Room Heating Off If No Person For 10 Min
  id: '1599910386111'
  description: 'automation.en_suite_room_heating_off_if_no_person_in_daytime'
  trigger:
  - minutes: /10
    platform: time_pattern
  - entity_id: binary_sensor.en_suite_room_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:10:00
  condition:
  - condition: state
    entity_id: binary_sensor.en_suite_room_motion_sensor_motion
    for: 00:10:00
    state: 'off'
  action:
  - data: {}
    entity_id: automation.en_suite_room_heating_based_on_temerature_sensor
    service: automation.turn_off
  - data: {}
    entity_id: automation.en_suite_room_heating_on_if_person_present
    service: automation.turn_on
  - service: climate.set_hvac_mode
    entity_id: climate.en_suite_room
    data:
      hvac_mode: auto
  mode: single





- alias: H-ET En-suite Toilet Heating Set to 22 If Person Present
  id: '1600014380333'
  description: 'automation.en_suite_toilet_heating_on_if_person_present'
  trigger:
  - entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition: []
  action:
  - data:
      hvac_mode: heat
    entity_id: climate.en_suite_toilet
    service: climate.set_hvac_mode
  - data:
      temperature: 22
    entity_id: climate.en_suite_toilet
    service: climate.set_temperature
  - data: {}
    entity_id: automation.en_suite_toilet_heating_on_if_person_present
    service: automation.turn_off
  mode: single





- alias: H-ET En-suite Toilet Heating Off If No Person For 10 Min
  id: '1600015749333'
  description: 'automation.en_suite_toilet_heating_off_if_no_person_for_15_min'
  trigger:
  - entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:10:00
  - minutes: /10
    platform: time_pattern
  condition:
  - condition: state
    entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
    for: 00:10:00
    state: 'off'
  action:
  - service: climate.set_hvac_mode
    entity_id: climate.en_suite_toilet
    data:
      hvac_mode: auto
  - data: {}
    entity_id: automation.en_suite_toilet_heating_on_if_person_present
    service: automation.turn_on
  mode: single

###############################################
#
# Lighting Automation based on motion sensors
#
###############################################


# En-suite Toilet Lights
- alias: L-GT En-suite Toilet Lights On If Person Present and Dark
  id: '1603640020013'
  description: ''
  trigger:
  - entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
  - condition: and
    conditions:
    - after: '00:00:01'
      before: '00:00:00'
      condition: time
    - condition: and
      conditions:
      - entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
        condition: state
        state: 'on'
      - entity_id: sensor.en_suite_toilet_motion_sensor_light
        condition: numeric_state
        below: '50'
  action:
  - data: {}
    entity_id: switch.en_suite_toilet_light
    service: switch.turn_on
  mode: single



- alias: L-GT En-suite Toilet Lights Off If No Person For 10 Min And Door Closed
  id: '1603640020014'
  description: ''
  trigger:
  - entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:10:00
  condition:
  - condition: and
    conditions:
    - after: '00:00:01'
      before: '00:00:00'
      condition: time
    - entity_id: binary_sensor.en_suite_toilet_door
      condition: state
      state: 'off'
    - entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
      condition: state
      state: 'off'
      for: 00:10:00
  action:
  - data: {}
    entity_id: switch.en_suite_toilet_light
    service: switch.turn_off
  mode: single


- alias: L-GT En-suite Toilet Lights Off If No Person For 2 Min And Door Closed
  id: '1603640020015'
  description: ''
  trigger:
  - entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:02:00
  condition:
  - condition: and
    conditions:
    - after: '00:00:01'
      before: '00:00:00'
      condition: time
    - entity_id: binary_sensor.en_suite_toilet_door
      condition: state
      state: 'on'
    - entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
      condition: state
      state: 'off'
      for: 00:02:00
  action:
  - data: {}
    entity_id: switch.en_suite_toilet_light
    service: switch.turn_off
  mode: single