# Kitchen
# - Heating/Hot Water automation
# - Lighting automation based on motion sensors
# - Lighting/Extractor control based on buttons
# - Extractor auotmation based on temperature
# - TV auto turn-off based on motion sensors
#
###############################################
#
# Heating Automation based on motion sensors
#
###############################################

- alias: H-KC Kitchen Heating Set to 20 If Person Present
  id: '1599609685194'
  description: 'automation.kitchen_heating_on_if_people_present'
  trigger:
  - entity_id: 
      - binary_sensor.kitchen_table_motion_sensor_motion
      - binary_sensor.kitchen_worktop_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  # Queued mode guarentees no race
  mode: queued    
  action:
  # Remove instances due to race conditions
  - condition: state
    entity_id: automation.kitchen_heating_on_if_people_present
    state:     'on'  
  # Turn on heating on repeated short presence or longer presence
  - choose:
    # IF - first time entering, set the flag
    #      Longer presence will turn on heating       
    - conditions:
      - condition: state
        entity_id: input_boolean.kitchen_short_presence
        state:     'off'
      sequence:
      # set the short presence flag
      - service:   input_boolean.turn_on
        entity_id: input_boolean.kitchen_short_presence
      # Delay 1.5 min and test motion sensor 
      - delay:     00:01:45
      - condition: or
        conditions:
        - condition: state
          entity_id: binary_sensor.kitchen_table_motion_sensor_motion
          state:     'on'
        - condition: state
          entity_id: binary_sensor.kitchen_worktop_motion_sensor_motion
          state:     'on'
      # Longer presence will turn on heating       
      - service: script.kitchen_set_heating_temp_with_state_maintaince
    # ELSE - Repeated short presence will turn on heating
    default:    
      - service: script.kitchen_set_heating_temp_with_state_maintaince

  

- alias: H-KC Kitchen Heating Off If No Person
  id: '1599609374841'
  description: 'automation.kitchen_heating_off_when_no_person'
  trigger:
  - entity_id: binary_sensor.kitchen_table_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:05:00
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: state
    entity_id: binary_sensor.kitchen_table_motion_sensor_motion
    for: 00:05:00
    state: 'off'
  action:
  # turn off heating
  - service: climate.set_hvac_mode
    entity_id: climate.kitchen
    data:
      hvac_mode: auto
  - data: {}
    entity_id: automation.kitchen_heating_on_if_people_present
    service: automation.turn_on
  # Clear flags
  - service:   input_boolean.turn_off
    entity_id: input_boolean.kitchen_short_presence  


- alias: W-KC Kitchen Drinking Hot Water On If Person Persent
  description: ''
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    entity_id:
      - binary_sensor.kitchen_table_motion_sensor_motion
      - binary_sensor.kitchen_worktop_motion_sensor_motion
      - binary_sensor.living_room_sofa_motion_sensor_motion
      - binary_sensor.living_room_tv_motion_sensor_motion
  condition: []
  action:
  - service: switch.turn_on
    entity_id: switch.kitchen_drinking_hot_water



- alias: W-KC Kitchen Drinking Hot Water Off If No Person
  description: ''
  trigger:
  - platform: state
    from: 'on'
    to: 'off'
    for: 00:10:00
    entity_id:
      - binary_sensor.kitchen_table_motion_sensor_motion
      - binary_sensor.kitchen_worktop_motion_sensor_motion
      - binary_sensor.living_room_sofa_motion_sensor_motion
      - binary_sensor.living_room_tv_motion_sensor_motion
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: state
    for: 00:10:00
    state: 'off'
    entity_id:
      - binary_sensor.kitchen_table_motion_sensor_motion
      - binary_sensor.kitchen_worktop_motion_sensor_motion
      - binary_sensor.living_room_sofa_motion_sensor_motion
      - binary_sensor.living_room_tv_motion_sensor_motion
  action:
  - service: switch.turn_off
    entity_id: switch.kitchen_drinking_hot_water



###############################################
#
# Lighting Automation based on motion sensors
#
###############################################
# Kitchen Decro Lights
- alias: L-KC Kitchen Decro Lights On If People Are Around
  description: ''
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    entity_id:
      - binary_sensor.ground_corridor_motion_sensor_motion
      - binary_sensor.first_corridor_motion_sensor_motion
      - binary_sensor.kitchen_table_motion_sensor_motion
      - binary_sensor.kitchen_worktop_motion_sensor_motion
  condition: []
  action:
  - service: switch.turn_on
    entity_id:
      - switch.kitchen_decro_light


- alias: L-KC Kitchen Decro Lights Off If People Are Not Around
  description: ''
  trigger:
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: state
    state: 'off'
    for: 00:10:00
    entity_id:
      - binary_sensor.ground_corridor_motion_sensor_motion
      - binary_sensor.first_corridor_motion_sensor_motion
      - binary_sensor.kitchen_table_motion_sensor_motion
      - binary_sensor.kitchen_worktop_motion_sensor_motion
  action:
  - service: switch.turn_off
    entity_id:
      - switch.kitchen_decro_light


# Kitchen
- alias: L-KC Kitchen Lights On If Person Present and Dark In Daytime
  id: '1603640029617'
  description: 'automation.kitchen_lights_on_if_person_present_and_dark_in_daytime'
  trigger:
  - entity_id: binary_sensor.kitchen_table_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  - entity_id: binary_sensor.kitchen_worktop_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: and
      conditions:
      - entity_id: binary_sensor.kitchen_table_motion_sensor_motion
        condition: state
        state: 'on'
      - entity_id: sensor.kitchen_table_motion_sensor_light
        condition: numeric_state
        below: '30'
    - after: '06:00:00'
      before: '00:00:00'
      condition: time
  action:
  - data: {}
    service: script.kitchen_all_wall_lights_turn_on




- alias: L-KC Kitchen Night Lights On If Person Present and Dark In Nighttime
  id: '1603640029618'
  description: ''
  trigger:
  - entity_id: binary_sensor.kitchen_table_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  - entity_id: binary_sensor.kitchen_worktop_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: and
      conditions:
      - entity_id: binary_sensor.kitchen_table_motion_sensor_motion
        condition: state
        state: 'on'
      - entity_id: sensor.kitchen_table_motion_sensor_light
        condition: numeric_state
        below: '30'
    - after: '00:00:00'
      before: '06:00:00'
      condition: time
  action:
  - data: {}
    service: script.kitchen_dining_lights_and_floor_led_turn_on



- alias: L-KC Kitchen All Lights and Appliances Off If No Person For 10 Min
  id: '1593556938732'
  description: 'automation.kitchen_all_lights_and_appliances_off_if_no_person'
  trigger:
  - minutes: /5
    platform: time_pattern
  - entity_id: binary_sensor.kitchen_table_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:10:00
  - entity_id: binary_sensor.kitchen_worktop_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:10:00
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.kitchen_table_motion_sensor_motion
      state: 'off'
      for: 00:10:00
    - condition: state
      entity_id: binary_sensor.kitchen_worktop_motion_sensor_motion
      state: 'off'
      for: 00:10:00
  action:
  - data: {}
    service: script.kitchen_all_lights_and_appliances_turn_off




- alias: L-KC Kitchen Worktop And Ceiling Lights On If Person Present In Worktop In Daytime
  id: '1603640020051'
  description: ''
  trigger:
  - entity_id: binary_sensor.kitchen_worktop_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
    - after: '06:00:00'
      before: '00:00:00'
      condition: time
  action:
  - data: {}
    service: script.kitchen_worktop_lights_turn_on
  - data: {}
    entity_id: switch.kitchen_ceiling_light
    service: switch.turn_on




- alias: L-KC Kitchen WorkTop Lights Off If No Person Present In Worktop For 5 Min
  description: ''
  trigger:
  - entity_id: binary_sensor.kitchen_worktop_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:05:00
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: state
    entity_id: binary_sensor.kitchen_worktop_motion_sensor_motion
    for: 00:05:00
    state: 'off'
  action:
  - data: {}
    service: script.kitchen_worktop_lights_turn_off



###############################################
#
# Lighting/Extractor control based on buttons
#
###############################################


- alias: B-KC Kitchen Turn Off Worktop LED When Turning Off Kitchen Ceiling Lights
  id: '1603132703022'
  description: ''
  trigger:
  - entity_id: switch.kitchen_ceiling_light
    platform: state
    from: 'on'
    to: 'off'
  action:
  - data: {}
    entity_id: script.kitchen_worktop_lights_turn_off
    service: script.turn_on


- alias: B-KC Kitchen Button Single Press - Toggle Extractor and Disable Turn On Automation For Some Time
  id: '1603132703122'
  trigger:
  - platform: state
    entity_id: sensor.kitchen_worktop_button
    to: single
  action:
  - entity_id: switch.kitchen_extractor
    service: switch.toggle
  mode: restart


- alias: B-KC Kitchen Light - Right/Double Press - Turn off all kitchen lights
  id: '1603132703322'
  trigger:
  - platform: state
    entity_id: sensor.kitchen_light_wall_button
    to: button_3_single
  - platform: state
    entity_id: sensor.kitchen_light_wall_button
    to: button_1_double
  - platform: state
    entity_id: sensor.kitchen_light_wall_button
    to: button_2_double
  - platform: state
    entity_id: sensor.kitchen_light_wall_button
    to: button_3_double
  action:
    service: script.kitchen_all_lights_and_appliances_turn_off



###############################################
#
# Extractor auotmation based on temperature
#
###############################################

- alias: E-KC Kitchen Extractor On If Temperature Is High
  id: '1603640029718'
  description: 'automation.kitchen_extractor_on_if_temperature_is_high'
  trigger:
  - entity_id: sensor.mi_temperature_kitchen_hob_temperature_sensor
    platform: numeric_state
    above: 25
  condition:
  action:
  - service: switch.turn_on
    entity_id: switch.kitchen_extractor
  # Ignore any trigger within 2 hour as the mode is single
  # the second action will be ignored until this action is finished.
  - delay: 02:00:00


#################################################################
#
# Sonos Speakers Grouping/Ungrouping Based On Motion Sensor
#
#################################################################

- alias: S-KC Kitchen Group Its Speaker If People Present
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    entity_id:
      - binary_sensor.kitchen_table_motion_sensor_motion
      - binary_sensor.kitchen_worktop_motion_sensor_motion
  condition: 
  - condition: state
    entity_id: input_boolean.follow_music
    state: 'on'  
  # The controller player must be playing music (not paused)  
  - condition: template
    value_template: >
      {% if states('media_player.' + states('input_select.music_controller')) == 'playing' %}
        true
      {% else %}
        false
      {% endif %}    
  action:
  # Add this room speaker into the group
  - service: script.add_sonos_into_speaker_group
    data: 
      target_player: media_player.kitchen_sonos


- alias: S-KC Kitchen Ungroup/Pause Its Speaker If No People
  trigger:
  - platform: state
    from: 'on'
    to: 'off'
    for: 00:10:00
    entity_id:
      - binary_sensor.kitchen_table_motion_sensor_motion
      - binary_sensor.kitchen_worktop_motion_sensor_motion
  - minutes: /5
    platform: time_pattern      
  condition: 
  - condition: state
    entity_id:
      - binary_sensor.kitchen_table_motion_sensor_motion
      - binary_sensor.kitchen_worktop_motion_sensor_motion
    for: 00:10:00
    state: 'off'    
  action:
  - choose:
    # IF - music follower is on
    - conditions:
      - condition: state
        entity_id: input_boolean.follow_music
        state: 'on'      
      sequence:
      # Remove this room speaker from the group
      - service: script.remove_sonos_from_speaker_group
        data: 
          target_player: media_player.kitchen_sonos
  # Pause this room speaker in case it is the last item in the group 
  # or music follower is off
  - service: script.pause_sonos_if_sole_speaker_group
    data: 
      target_player: media_player.kitchen_sonos


#################################################################
#
# TV auto turn-off based on motion sensors
#
#################################################################
- alias: TV-KC Kitchen Turn Off TV If No Person
  trigger:
  - platform: state
    from: 'on'
    to: 'off'
    for: 00:10:00
    entity_id:
      - binary_sensor.kitchen_table_motion_sensor_motion
      - binary_sensor.kitchen_worktop_motion_sensor_motion
  - minutes: /5
    platform: time_pattern      
  condition: 
  - condition: state
    entity_id:
      - binary_sensor.kitchen_table_motion_sensor_motion
      - binary_sensor.kitchen_worktop_motion_sensor_motion
    for: 00:10:00
    state: 'off'    
  action:
  # Switch Off TV
  - service:   switch.turn_off
    entity_id: switch.kitchen_tv    

