# Living Room
# - Heating automation
# - Lighting automation based on motion sensors
# - Lighting automation based on buttons
# - Sonos Speakers Grouping/Ungrouping Based On Motion Sensor
#
###############################################
#
# Heating Automation based on motion sensors
#
###############################################


- alias: H-LR Living Room Heating Set to 22 If Person Present
  id: '1599611100701'
  description: 'automation.living_room_heating_on_if_people_present'
  trigger:
  - entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition: []
  action:
  - data:
      hvac_mode: heat
    entity_id: climate.living_room
    service: climate.set_hvac_mode
  - data:
      temperature: 22
    entity_id: climate.living_room
    service: climate.set_temperature
  - data:
      stop_actions: false
    entity_id: automation.living_room_heating_on_if_people_present
    service: automation.turn_off





- alias: H-LR Living Room Heating Off If No Person For 10 Min
  id: '1599611453836'
  description: 'automation.living_room_heating_off_if_no_people'
  trigger:
  - entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:10:00
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: state
    entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
    for: 00:10:00
    state: 'off'
  action:
  - service: climate.set_hvac_mode
    entity_id: climate.living_room
    data:
      hvac_mode: auto
  - data: {}
    entity_id: automation.living_room_heating_on_if_people_present
    service: automation.turn_on


###############################################
#
# Lighting Automation based on motion sensors
#
###############################################

# Gardens
- alias: L-LR Garden and Corridor Lights On If Person Present Around Door
  description: ''
  trigger:
  - entity_id: 
      - binary_sensor.garden_sliding_door_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
    - condition: and
      conditions:
      - entity_id: binary_sensor.garden_sliding_door_motion_sensor_motion
        condition: state
        state: 'on'
      - entity_id: sensor.garden_sliding_door_motion_sensor_light
        condition: numeric_state
        below: '30'
  action:
  - service: switch.turn_on
    entity_id: 
      - switch.garden_light
      - switch.garden_extension_lead_switch_1
  - service: script.living_room_landing_lights_turn_on
  - service: script.corridor_lights_turn_on_from_ground_floor


# Gardens
- alias: L-LR Garden and Corridor Lights On If Person Present Around Garden
  description: ''
  trigger:
  - entity_id: 
      - binary_sensor.garden_bike_shed_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
    - condition: and
      conditions:
      - entity_id: binary_sensor.garden_bike_shed_motion_sensor_motion
        condition: state
        state: 'on'
      - entity_id: sensor.garden_bike_shed_motion_sensor_light
        condition: numeric_state
        below: '30'
  action:
  - service: switch.turn_on
    entity_id: 
      - switch.garden_light
      - switch.garden_extension_lead_switch_1



- alias: L-LR Garden Lights Off If No Person Present For 5 Min
  description: ''
  trigger:
  - entity_id: 
    - binary_sensor.garden_sliding_door_motion_sensor_motion
    - binary_sensor.garden_bike_shed_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:05:00
  - minutes: /5
    platform: time_pattern
  condition:
  - entity_id: 
    - binary_sensor.garden_sliding_door_motion_sensor_motion
    - binary_sensor.garden_bike_shed_motion_sensor_motion
    condition: state
    state: 'off'
    for: 00:05:00
  action:
  - service: switch.turn_off
    entity_id: 
      - switch.garden_light
      - switch.garden_extension_lead_switch_1




# Living Room
- alias: L-LR Living Room Lights On If Person Present
  id: '1603640031661'
  description: 'automation.l_lr_living_room_lights_on_if_person_present'
  trigger:
  - entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  - entity_id: binary_sensor.living_room_tv_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
    - condition: or
      conditions:
      # Sofa Motion Sensor with Dark Room
      - condition: and
        conditions:
        - entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
          condition: state
          state: 'on'
        - entity_id: sensor.living_room_sofa_motion_sensor_light
          condition: numeric_state
          below: '40'
      # TV Motion Sensor with Dark Outside
      - condition: and
        conditions:
        - entity_id: binary_sensor.living_room_tv_motion_sensor_motion
          condition: state
          state: 'on'
        - entity_id: sensor.master_room_light_meter
          condition: numeric_state
          below: '30'
  action:
  - service: script.living_room_landing_lights_turn_on




- alias: L-LR Living Room Lights Off If No Person For 10 Min
  id: '1603640031662'
  description: ''
  trigger:
  - entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:10:00
  - entity_id: binary_sensor.living_room_tv_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:10:00
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: state
    entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
    for: 00:10:00
    state: 'off'
  - condition: state
    entity_id: binary_sensor.living_room_tv_motion_sensor_motion
    for: 00:10:00
    state: 'off'
  action:
  - service: script.living_room_all_lights_turn_off



###############################################
#
# Lighting Automation based on buttons
#
###############################################

- alias: B-LR Living Room Wall/Sofa - Single Press - Toggle Landing Lights
  id: '1603641040070'
  trigger:
  - platform: state
    entity_id: sensor.living_room_sofa_button
    to: single
  - platform: state
    entity_id: sensor.living_room_ceiling_light_button
    to: '1'
  action:
  - service: script.living_room_landing_lights_toggle



- alias: B-LR Living Room Wall Switch - Double Press - Turn Off All Lights
  trigger:
  - platform: state
    entity_id: sensor.living_room_ceiling_light_button
    to: '2'
  action:
  - service: script.living_room_all_lights_turn_off



- alias: B-LR Living Room Sofa - Double Press - Toggle Ceiling Lights
  id: '1603641040071'
  trigger:
  - platform: state
    entity_id: sensor.living_room_sofa_button
    to: double
  action:
  - entity_id: switch.living_room_ceiling_light
    service: switch.toggle



- alias: B-LR Living Room Sofa - Tripple Press - Turn off lights - Movie Scene For 2 Hours
  id: '1603641040072'
  trigger:
  - platform: state
    entity_id: sensor.living_room_sofa_button
    to: triple
  action:
  - choose:
    # IF movie scene is off, turn off lights and its automation for 2 hours for movie scene
    - conditions:
      - condition: state
        entity_id: automation.l_lr_living_room_lights_on_if_person_present
        state: 'on'
      sequence:
        # Turn off auto light automation and lights
        - service: automation.turn_off
          entity_id: automation.l_lr_living_room_lights_on_if_person_present
        - service: script.living_room_landing_lights_turn_off
        - entity_id: switch.living_room_ceiling_light
          service: switch.turn_off
        # Delay of some time and turn on back auto lights up
        - delay: '02:00:00'
        - service: automation.turn_on
          entity_id: automation.l_lr_living_room_lights_on_if_person_present

    # ELSE - if movie scene is on, turn off movie scene and turn on lights and its automation
    default:
      - service: script.living_room_landing_lights_turn_on
      - service: automation.turn_on
        entity_id: automation.l_lr_living_room_lights_on_if_person_present
  mode: restart
  
  
#################################################################
#
# Sonos Speakers Grouping/Ungrouping Based On Motion Sensor
#
#################################################################

- alias: S-LR Living Room Group Its Speaker If People Present
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    entity_id:
      - binary_sensor.living_room_sofa_motion_sensor_motion
      - binary_sensor.living_room_tv_motion_sensor_motion
  condition: 
  - condition: state
    entity_id: input_boolean.follow_music
    state: 'on'  
  # The controller player must be playing music (not paused)  
  - condition: template
    value_template: >
      {% if states('media_player.' + states('input_select.music_controller')) == 'playing' %}
        true
      {% else %}
        false
      {% endif %}    
  action:
  # Add this room speaker into the group
  - service: script.add_sonos_into_speaker_group
    data: 
      target_player: media_player.living_room_sonos


- alias: S-LR Living Room Ungroup/Pause Its Speaker If No People
  trigger:
  - platform: state
    from: 'on'
    to: 'off'
    for: 00:10:00
    entity_id:
      - binary_sensor.living_room_sofa_motion_sensor_motion
      - binary_sensor.living_room_tv_motion_sensor_motion
  - minutes: /5
    platform: time_pattern      
  condition: 
  - condition: state
    entity_id: input_boolean.follow_music
    state: 'on'  
  - condition: state
    entity_id:
      - binary_sensor.living_room_sofa_motion_sensor_motion
      - binary_sensor.living_room_tv_motion_sensor_motion
    for: 00:10:00
    state: 'off'    
  action:
  # Remove this room speaker from the group
  - service: script.remove_sonos_from_speaker_group
    data: 
      target_player: media_player.living_room_sonos
  # Pause this room speaker in case it is the last item in the group 
  - service: media_player.media_pause
    entity_id: media_player.master_room_sonos
    
    

- alias: S- Maintain Music Follower State 
  trigger:
  - platform: state
    entity_id:
      - media_player.living_room_sonos
      - media_player.master_room_sonos
      - media_player.kitchen_sonos
    to:
      - "idle"
      - "playing"
      - "paused"
      - "off"
  - minutes: /5
    platform: time_pattern      
  condition: []
  action:
  - choose:
    - conditions:
    # IF any Sonos is playing, turn on music follower
      - condition: or
        conditions:
        - condition: state
          state:     "playing"
          entity_id: media_player.living_room_sonos
        - condition: state
          state:     "playing"
          entity_id: media_player.master_room_sonos
        - condition: state
          state:     "playing"
          entity_id: media_player.kitchen_sonos
      sequence:
        - service: input_boolean.turn_on
          entity_id: input_boolean.follow_music      
    # ELSE - turn off music follower
    default:
      - service: input_boolean.turn_off
        entity_id: input_boolean.follow_music      


- alias: S- Set Music Master Speaker When The Only One Is Playing
  trigger:
  - platform: state
    entity_id:
      - media_player.living_room_sonos
      - media_player.master_room_sonos
      - media_player.kitchen_sonos
    to:
      - "idle"
      - "playing"
      - "paused"
      - "off"
  - minutes: /5
    platform: time_pattern      
  condition: []
  action:
  - choose:
    # IF - only kitchen sonos is playing - set it as master speaker
    - conditions:
      - condition: state
        state:     "playing"
        entity_id: media_player.kitchen_sonos
      - condition: not
        conditions:
        - condition: state
          state:     "playing"
          entity_id: media_player.living_room_sonos
        - condition: state
          state:     "playing"
          entity_id: media_player.master_room_sonos
      sequence:
        - service: input_select.select_option
          entity_id: input_select.music_controller
          data:
            option:  kitchen_sonos
    # ELIF only living room sonos is playing - set it as master speaker
    - conditions:
      - condition: state
        state:     "playing"
        entity_id: media_player.living_room_sonos
      - condition: not
        conditions:
        - condition: state
          state:     "playing"
          entity_id: media_player.kitchen_sonos
        - condition: state
          state:     "playing"
          entity_id: media_player.master_room_sonos
      sequence:
        - service: input_select.select_option
          entity_id: input_select.music_controller
          data:
            option:  living_room_sonos
    # IF only kitchen sonos is playing - set it as master speaker
    - conditions:
      - condition: state
        state:     "playing"
        entity_id: media_player.master_room_sonos
      - condition: not
        conditions:
        - condition: state
          state:     "playing"
          entity_id: media_player.living_room_sonos
        - condition: state
          state:     "playing"
          entity_id: media_player.kitchen_sonos
      sequence:
        - service: input_select.select_option
          entity_id: input_select.music_controller
          data:
            option:  master_room_sonos
  

    