# Living Room
# - Heating automation
# - Lighting automation based on motion sensors
# - Lighting automation based on buttons
#


###############################################
#
# Heating Automation based on motion sensors
#
###############################################


- alias: H-LR Living Room Heating Set to 22 If Person Present
  id: '1599611100701'
  description: 'automation.living_room_heating_on_if_people_present'
  trigger:
  - entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition: []
  action:
  - data:
      hvac_mode: heat
    entity_id: climate.living_room
    service: climate.set_hvac_mode
  - data:
      temperature: 22
    entity_id: climate.living_room
    service: climate.set_temperature
  - data:
      stop_actions: false
    entity_id: automation.living_room_heating_on_if_people_present
    service: automation.turn_off





- alias: H-LR Living Room Heating Off If No Person For 10 Min
  id: '1599611453836'
  description: 'automation.living_room_heating_off_if_no_people'
  trigger:
  - entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:10:00
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: state
    entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
    for: 00:10:00
    state: 'off'
  action:
  - service: climate.set_hvac_mode
    entity_id: climate.living_room
    data:
      hvac_mode: auto
  - data: {}
    entity_id: automation.living_room_heating_on_if_people_present
    service: automation.turn_on


###############################################
#
# Lighting Automation based on motion sensors
#
###############################################

# Gardens
- alias: L-LR Garden Lights On If Person Present also turning on Living Room and Cooridor Lights
  description: ''
  trigger:
  - entity_id: binary_sensor.garden_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
    - condition: and
      conditions:
      - entity_id: binary_sensor.garden_motion_sensor_motion
        condition: state
        state: 'on'
      - entity_id: sensor.garden_motion_sensor_light
        condition: numeric_state
        below: '30'
  action:
  - service: switch.turn_on
    entity_id:
      - switch.garden_light
      - switch.living_room_tree_light
  - service: script.living_room_landing_lights_turn_on
  - service: script.corridor_lights_turn_on_from_ground_floor




- alias: L-LR Garden Lights Off If No Person Present For 5 Min
  id: '1603640040052'
  description: ''
  trigger:
  - entity_id: binary_sensor.garden_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:05:00
  - minutes: /5
    platform: time_pattern
  condition:
  - entity_id: binary_sensor.garden_motion_sensor_motion
    condition: state
    state: 'off'
    for: 00:05:00
  action:
  - data: {}
    entity_id: switch.garden_light
    service: switch.turn_off




# Living Room
- alias: L-LR Living Room Lights On If Person Present
  id: '1603640031661'
  description: 'automation.l_lr_living_room_lights_on_if_person_present'
  trigger:
  - entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  - entity_id: binary_sensor.living_room_tv_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
    - condition: or
      conditions:
      # Sofa Motion Sensor with Dark Room
      - condition: and
        conditions:
        - entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
          condition: state
          state: 'on'
        - entity_id: sensor.living_room_sofa_motion_sensor_light
          condition: numeric_state
          below: '40'
      # TV Motion Sensor with Dark Outside
      - condition: and
        conditions:
        - entity_id: binary_sensor.living_room_tv_motion_sensor_motion
          condition: state
          state: 'on'
        - entity_id: sensor.master_room_light_meter
          condition: numeric_state
          below: '30'
  action:
  - service: script.living_room_landing_lights_turn_on
  - service: switch.turn_on
    entity_id:
      - switch.living_room_tree_light




- alias: L-LR Living Room Lights Off If No Person For 10 Min
  id: '1603640031662'
  description: ''
  trigger:
  - entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:10:00
  - entity_id: binary_sensor.living_room_tv_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:10:00
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: state
    entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
    for: 00:10:00
    state: 'off'
  - condition: state
    entity_id: binary_sensor.living_room_tv_motion_sensor_motion
    for: 00:10:00
    state: 'off'
  action:
  - service: script.living_room_all_lights_turn_off



###############################################
#
# Lighting Automation based on buttons
#
###############################################

- alias: B-LR Living Room Wall/Sofa - Single Press - Toggle Landing Lights
  id: '1603641040070'
  trigger:
  - platform: state
    entity_id: sensor.living_room_sofa_button
    to: single
  - platform: state
    entity_id: sensor.living_room_ceiling_light_button
    to: '1'
  action:
  - service: script.living_room_landing_lights_toggle



- alias: B-LR Living Room Wall Switch - Double Press - Turn Off All Lights
  trigger:
  - platform: state
    entity_id: sensor.living_room_ceiling_light_button
    to: '2'
  action:
  - service: script.living_room_all_lights_turn_off



- alias: B-LR Living Room Sofa - Double Press - Toggle Ceiling Lights
  id: '1603641040071'
  trigger:
  - platform: state
    entity_id: sensor.living_room_sofa_button
    to: double
  action:
  - entity_id: switch.living_room_ceiling_light
    service: switch.toggle



- alias: B-LR Living Room Sofa - Tripple Press - Turn off lights - Movie Scene For 2 Hours
  id: '1603641040072'
  trigger:
  - platform: state
    entity_id: sensor.living_room_sofa_button
    to: triple
  action:
  - choose:
    # IF movie scene is off, turn off lights and its automation for 2 hours for movie scene
    - conditions:
      - condition: state
        entity_id: automation.l_lr_living_room_lights_on_if_person_present
        state: 'on'
      sequence:
        # Turn off auto light automation and lights
        - service: automation.turn_off
          entity_id: automation.l_lr_living_room_lights_on_if_person_present
        - service: script.living_room_landing_lights_turn_off
        - entity_id: switch.living_room_ceiling_light
          service: switch.turn_off
        # Delay of some time and turn on back auto lights up
        - delay: '02:00:00'
        - service: automation.turn_on
          entity_id: automation.l_lr_living_room_lights_on_if_person_present

    # ELSE - if movie scene is on, turn off movie scene and turn on lights and its automation
    default:
      - service: script.living_room_landing_lights_turn_on
      - service: automation.turn_on
        entity_id: automation.l_lr_living_room_lights_on_if_person_present
  mode: restart