# Master Room
# Master Toilet
# - Heating automation
# - Lighting automation based on motion sensors
# - Lighting/Curtain automation based on buttons
# - Lighting/Curtain autmation based on time


###############################################
#
# Heating Automation based on motion sensors
#
###############################################


- alias: H-MR Master Room Heating Set to 22 If Person Present
  id: '1599909943770'
  description: 'automation.master_room_heating_on_if_person_present'
  trigger:
  - entity_id: binary_sensor.master_room_bed_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition: []
  action:
  - data:
      hvac_mode: heat
    entity_id: climate.master_room
    service: climate.set_hvac_mode
  - data:
      temperature: >
        {% if now().hour >= 18 or now().hour < 9 %}
          23
        {% else %}
          21
        {% endif %}
    entity_id: climate.master_room
    service: climate.set_temperature
  - data:
      stop_actions: false
    entity_id: automation.master_room_heating_on_if_person_present
    service: automation.turn_off
  mode: single



- alias: H-MR Master Room Heating Off If No Person For 10 Min In Daytime
  id: '1599910386760'
  description: 'automation.master_room_heating_off_if_no_person_in_daytime'
  trigger:
  - entity_id: binary_sensor.master_room_bed_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:10:00
  - minutes: /10
    platform: time_pattern
  condition:
  - after: '9:00:00'
    before: '21:00:00'
    condition: time
  - condition: state
    entity_id: binary_sensor.master_room_bed_motion_sensor_motion
    for: 00:10:00
    state: 'off'
  action:
  - service: climate.set_hvac_mode
    entity_id: climate.master_room
    data:
      hvac_mode: auto
  - data: {}
    entity_id: automation.master_room_heating_on_if_person_present
    service: automation.turn_on
  mode: single



- alias: H-MT Master Toilet Heating Set to 20 If Person Present
  id: '1600014380137'
  description: 'automation.master_toilet_heating_on_if_person_present'
  trigger:
  - entity_id: binary_sensor.master_toilet_basin_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  - entity_id: binary_sensor.master_toilet_shower_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition: []
  action:
  - data:
      hvac_mode: heat
    entity_id: climate.master_toilet
    service: climate.set_hvac_mode
  - data:
      temperature: 20
    entity_id: climate.master_toilet
    service: climate.set_temperature
  - data:
      stop_actions: false
    entity_id: automation.master_toilet_heating_on_if_person_present
    service: automation.turn_off
  mode: single



- alias: H-MT Master Toilet Heating Off If No Person For 10 Min
  id: '1600015749043'
  description: 'automation.master_toilet_heating_off_if_no_person'
  trigger:
  - minutes: /10
    platform: time_pattern
  - entity_id: binary_sensor.master_toilet_basin_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:10:00
  - entity_id: binary_sensor.master_toilet_shower_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:10:00
  - minutes: /10
    platform: time_pattern
  condition:
  - condition: state
    entity_id: binary_sensor.master_toilet_basin_motion_sensor_motion
    for: 00:10:00
    state: 'off'
  - condition: state
    entity_id: binary_sensor.master_toilet_shower_motion_sensor_motion
    for: 00:10:00
    state: 'off'
  action:
  - service: climate.set_hvac_mode
    entity_id: climate.master_toilet
    data:
      hvac_mode: auto
  - data: {}
    entity_id: automation.master_toilet_heating_on_if_person_present
    service: automation.turn_on
  mode: single


###############################################
#
# Lighting Automation based on motion sensors
#
###############################################

# Master Room Dressing Table Light
- alias: L-MR Master Room Dressing Table On If Person Present
  id: '1603640027683'
  description: ''
  trigger:
  - entity_id: binary_sensor.master_room_dressing_table_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: switch.master_room_dressing_table_light
    service: switch.turn_on
  mode: single


- alias: L-MR Master Room Dressing Table Off If No Person For 2 Min
  id: '1603640027689'
  description: ''
  trigger:
  - entity_id: binary_sensor.master_room_dressing_table_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:02:00
  - minutes: /10
    platform: time_pattern
  condition:
  - entity_id: binary_sensor.master_room_dressing_table_motion_sensor_motion
    condition: state
    state: 'off'
    for: 00:02:00
  action:
  - data: {}
    entity_id: switch.master_room_dressing_table_light
    service: switch.turn_off
  mode: single


- alias: L-MR Master Room LED Strip On For Some Time If People Are Walking In the Dark
  id: '1603640027693'
  description: ''
  mode: restart
  trigger:
  - entity_id: binary_sensor.master_room_tv_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  - entity_id: binary_sensor.master_room_drawer_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
  # In the night
  - entity_id: sensor.master_room_light_meter
    condition: numeric_state
    below: 5
  # When all lights off
  - entity_id: light.master_room_lamp_near_door
    condition: state
    state: 'off'
  - entity_id: light.master_room_lamp_near_wall
    condition: state
    state: 'off'
  - entity_id: light.master_room_bed_led_strip
    condition: state
    state: 'off'
  - entity_id: switch.master_room_bed_ceiling_light
    condition: state
    state: 'off'
  - entity_id: switch.master_room_landing_ceiling_light
    condition: state
    state: 'off'
  - entity_id: switch.master_room_dressing_table_light
    condition: state
    state: 'off'
  action:
  # Turn On LED Strip For An Hour (it can be manually turned off)
  - service: light.turn_on
    entity_id: light.master_room_bed_led_strip
  - delay: '01:00:00'
  - service: light.turn_off
    entity_id: light.master_room_bed_led_strip



# Master Toilet
- alias: L-MT Master Toilet Lights On If Person Present and Dark In Daytime
  id: '1603640027457'
  description: ''
  trigger:
  - entity_id: binary_sensor.master_toilet_basin_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  - entity_id: binary_sensor.master_toilet_shower_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
  - after: '7:00:00'
    before: '23:30:00'
    condition: time
  - condition: or
    conditions:
    - condition: and
      conditions:
      - entity_id: binary_sensor.master_toilet_basin_motion_sensor_motion
        condition: state
        state: 'on'
      - entity_id: sensor.master_toilet_basin_motion_sensor_light
        condition: numeric_state
        below: '50'
    - condition: and
      conditions:
      - entity_id: binary_sensor.master_toilet_shower_motion_sensor_motion
        condition: state
        state: 'on'
      - entity_id: sensor.master_toilet_shower_motion_sensor_light
        condition: numeric_state
        below: '10'
  action:
  - service: script.master_toilet_all_lights_turn_on
  mode: single

- alias: L-MT Master Toilet Lights On If Person Present and Dark In Daytime
  id: '1603640027457'
  description: ''
  trigger:
  - entity_id: binary_sensor.master_toilet_basin_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  - entity_id: binary_sensor.master_toilet_shower_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
  - after: '23:30:00'
    before: '00:07:00'
    condition: time
  - condition: or
    conditions:
    - condition: and
      conditions:
      - entity_id: binary_sensor.master_toilet_basin_motion_sensor_motion
        condition: state
        state: 'on'
      - entity_id: sensor.master_toilet_basin_motion_sensor_light
        condition: numeric_state
        below: '50'
    - condition: and
      conditions:
      - entity_id: binary_sensor.master_toilet_shower_motion_sensor_motion
        condition: state
        state: 'on'
      - entity_id: sensor.master_toilet_shower_motion_sensor_light
        condition: numeric_state
        below: '10'
  action:
  - service: switch.turn_on
    entity_id: 
     - switch.master_toilet_floor_led
  mode: single



- alias: L-MT Master Toilet Lights Off If No Person For 10 Min
  id: '1603640029094'
  description: ''
  trigger:
  - entity_id: binary_sensor.master_toilet_basin_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:10:00
  - entity_id: binary_sensor.master_toilet_shower_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:10:00
  - minutes: /10
    platform: time_pattern
  condition:
  - entity_id: binary_sensor.master_toilet_basin_motion_sensor_motion
    condition: state
    state: 'off'
    for: 00:10:00
  - entity_id: binary_sensor.master_toilet_shower_motion_sensor_motion
    condition: state
    state: 'off'
    for: 00:10:00
  action:
  - service: script.master_toilet_all_lights_turn_off
  mode: single


- alias: L-MT Master Toilet Lights Off If No Person For 2 Min And Door Open
  id: '1603640027495'
  description: ''
  trigger:
  - entity_id: binary_sensor.master_toilet_basin_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:02:00
  - entity_id: binary_sensor.master_toilet_shower_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:02:00
  - minutes: /10
    platform: time_pattern
  condition:
  - entity_id: binary_sensor.master_toilet_door
    condition: state
    state: 'on'
  - entity_id: binary_sensor.master_toilet_basin_motion_sensor_motion
    condition: state
    state: 'off'
    for: 00:02:00
  - entity_id: binary_sensor.master_toilet_shower_motion_sensor_motion
    condition: state
    state: 'off'
    for: 00:02:00
  action:
  - service: script.master_toilet_all_lights_turn_off
  mode: single


- alias: L-MT Master Toilet Dressing Lights On If Person Present In Daytime
  description: ''
  trigger:
  - entity_id: binary_sensor.master_toilet_dressing_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
  - after: '7:00:00'
    before: '23:30:00'      
    condition: time
  - entity_id: binary_sensor.master_toilet_dressing_motion_sensor_motion
    condition: state
    state: 'on'
  - entity_id: sensor.master_toilet_dressing_motion_sensor_light
    condition: numeric_state
    below: '50'
  action:
  - data: {}
    entity_id: switch.master_toilet_dressing_light
    service: switch.turn_on
  mode: single



- alias: L-MT Master Toilet Dressing Lights Off If No Person Present For 2 Min
  description: ''
  trigger:
  - entity_id: binary_sensor.master_toilet_dressing_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:02:00
  - minutes: /10
    platform: time_pattern
  condition:
    - entity_id: binary_sensor.master_toilet_dressing_motion_sensor_motion
      condition: state
      state: 'off'
      for: 00:02:00
  action:
  - data: {}
    entity_id: switch.master_toilet_dressing_light
    service: switch.turn_off
  mode: single





###############################################
#
# Lighting/Curatin Automation based on buttons
#
###############################################

# Master Room
- alias: B-MR Master Room Six Key - Middle Keys Double Press - Toggle Bedside Lights
  id: '1603640020890'
  trigger:
  - platform: state
    entity_id: sensor.master_room_six_key_button
    to: button_4_double
  - platform: state
    entity_id: sensor.master_room_six_key_button
    to: button_3_double
  action:
  - service: script.master_room_bedside_lights_toggle

- alias: B-MR Master Room Six Key - Middle Key 3 Single Press - Toggle Each Bedside Light Door
  id: '1603640020891'
  trigger:
  - platform: state
    entity_id: sensor.master_room_six_key_button
    to: button_3_single
  action:
  - entity_id: light.master_room_lamp_near_door
    service: light.toggle

- alias: B-MR Master Room Six Key - Middle Key 4 Single Press - Toggle Each Bedside Light Wall
  id: '1603640020892'
  trigger:
  - platform: state
    entity_id: sensor.master_room_six_key_button
    to: button_4_single
  action:
  - entity_id: light.master_room_lamp_near_wall
    service: light.toggle


- alias: B-MR Master Room Six Key - Right Keys Long Press - Toggle Blind Right
  id: '1603640020893'
  # This automation needs to restart to interrupt the previous run
  mode: restart
  trigger:
  - platform: state
    entity_id: sensor.master_room_six_key_button
    to: button_5_hold
  - platform: state
    entity_id: sensor.master_room_six_key_button
    to: button_6_hold
  action:
  - choose:
    # IF
    - conditions:
      - condition: state
        entity_id: input_boolean.master_room_right_blind_moving_in_progress
        state: 'off'
      sequence:
        # Mark the curtain as moving in progress and toggle the curtain
        - service: input_boolean.turn_on
          entity_id: input_boolean.master_room_right_blind_moving_in_progress
        - service: script.master_room_right_blind_toggle
        # Wait for curtain motor to finish and mark it as completed
        - delay: '00:01:30'
        - service: input_boolean.turn_off
          entity_id: input_boolean.master_room_right_blind_moving_in_progress
    # ELSE IF
    - conditions:
      - condition: state
        entity_id: input_boolean.master_room_right_blind_moving_in_progress
        state: 'on'
      sequence:
        # Stop the motor and mark it as stopped
        - service: cover.stop_cover
          entity_id: cover.master_room_blind_right
        - service: input_boolean.turn_off
          entity_id: input_boolean.master_room_right_blind_moving_in_progress


- alias: B-MR Master Room Six Key - Left Keys Long Press - Toggle Blind Left
  id: '1603640020897'
  # This automation needs to restart to interrupt the previous run
  mode: restart
  trigger:
  - platform: state
    entity_id: sensor.master_room_six_key_button
    to: button_1_hold
  - platform: state
    entity_id: sensor.master_room_six_key_button
    to: button_2_hold
  action:
  - choose:
    # IF
    - conditions:
      - condition: state
        entity_id: input_boolean.master_room_left_blind_moving_in_progress
        state: 'off'
      sequence:
        # Mark the curtain as moving in progress and toggle the curtain
        - service: input_boolean.turn_on
          entity_id: input_boolean.master_room_left_blind_moving_in_progress
        - service: script.master_room_left_blind_toggle
        # Wait for curtain motor to finish and mark it as completed
        - delay: '00:01:30'
        - service: input_boolean.turn_off
          entity_id: input_boolean.master_room_left_blind_moving_in_progress
    # ELSE IF
    - conditions:
      - condition: state
        entity_id: input_boolean.master_room_left_blind_moving_in_progress
        state: 'on'
      sequence:
        # Stop the motor and mark it as stopped
        - service: cover.stop_cover
          entity_id: cover.master_room_blind_left
        - service: input_boolean.turn_off
          entity_id: input_boolean.master_room_left_blind_moving_in_progress



- alias: B-MR Master Room Six Key - Middle Keys Long Press - Toggle Curtain
  id: '1603640020894'
  # This automation needs to restart to interrupt the previous run
  mode: restart
  trigger:
  - platform: state
    entity_id: sensor.master_room_six_key_button
    to: button_3_hold
  - platform: state
    entity_id: sensor.master_room_six_key_button
    to: button_4_hold
  action:
  - choose:
    # IF
    # REVISIT: this variable checking can be replaced by checking the position of the curtain
    - conditions:
      - condition: state
        entity_id: input_boolean.master_room_curtain_moving_in_progress
        state: 'off'
      sequence:
        # Mark the curtain as moving in progress and toggle the curtain
        - service: input_boolean.turn_on
          entity_id: input_boolean.master_room_curtain_moving_in_progress
        - service: script.master_room_curtain_toggle
        # Wait for curtain motor to finish and mark it as completed
        - delay: '00:00:10'
        - service: input_boolean.turn_off
          entity_id: input_boolean.master_room_curtain_moving_in_progress
    # ELSE IF
    - conditions:
      - condition: state
        entity_id: input_boolean.master_room_curtain_moving_in_progress
        state: 'on'
      sequence:
        # Stop the motor and mark it as stopped
        - service: cover.stop_cover
          entity_id: cover.master_room_curtain
        - service: input_boolean.turn_off
          entity_id: input_boolean.master_room_curtain_moving_in_progress

# Master Toilet
- alias: B-MT Master Toilet Wall Switch Single Press - Toggle Toilet Lights
  trigger:
  - platform: state
    entity_id: sensor.master_toilet_light_wall_button
    to: '1'
  action:
  - service: script.master_toilet_all_lights_toggle
  mode: single

- alias: B-MT Master Toilet Dressing Room Wall Switch Single Press - Turn On Dressing Room Lights/Turn Off All Toilet Lights
  mode: single
  trigger:
  - platform: state
    entity_id: sensor.master_toilet_dressing_light_wall_button
    to: '1'
  action:
  - choose:
    # IF - all lights off - turn on dressing room light
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: switch.master_toilet_floor_led
          state: 'off'
        - condition: state
          entity_id: switch.master_toilet_light
          state: 'off'
        - condition: state
          entity_id: switch.master_toilet_dressing_light
          state: 'off'          
      sequence:
        - service: switch.turn_on
          entity_id: switch.master_toilet_dressing_light
    # ELSE - some lights on - turn off all toilet lights and dressing room lights
    default:
      - service: script.master_toilet_all_lights_turn_off
      - service: switch.turn_off
        entity_id: switch.master_toilet_dressing_light
        

###############################################
#
# Lighting/Curtain autmation based on time
#
###############################################

- alias: T-MR Master Room Turn Off all Lights/Curtains at 2/3/4/5am
  id: '1602117522999'
  description: ''
  trigger:
  - at: 02:00:00
    platform: time
  - at: 03:00:00
    platform: time
  - at: 04:00:00
    platform: time
  - at: 05:00:00
    platform: time
  condition: []
  action:
  - service: script.master_room_close_all_curtains
  - service: script.master_room_lights_turn_off
  # Tuya Blind Sometimes is not online - make sure it is properly executed
  - delay: '00:00:05'
  - service: script.master_room_close_all_curtains
  - delay: '00:00:05'
  - service: script.master_room_close_all_curtains
  - delay: '00:00:05'
  - service: script.master_room_close_all_curtains
  mode: single

