

- alias: Turn Off All TVs at 2.3.4.5am
  id: '1602117522624'
  description: ''
  trigger:
  - at: 02:00:00
    platform: time
  - at: 03:00:00
    platform: time
  - at: 04:00:00
    platform: time
  - at: 05:00:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: media_player.living_room_tv
    service: media_player.turn_off



- alias: turn on tv - DOES NOT WORK - NEED WAKE-ON-LAN
  id: '1602118134986'
  description: ''
  trigger:
  - at: '12:00:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: media_player.living_room_tv
    service: media_player.turn_on


- alias: Living Room TV Off If No Person For 20 Min
  id: '1602118737375'
  description: ''
  trigger:
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: state
    entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
    for: 00:20:00
    state: 'off'
  action:
  - data:
      entity_id: media_player.living_room_tv
    service: media_player.turn_off





- alias: 'Restart HA at 5am After All Devices Restarted '
  id: '1602722452776'
  description: ''
  trigger:
  - at: 05:00:00
    platform: time
  condition: []
  action:
  - data: {}
    service: homeassistant.restart






